CREATE TABLE MEMS
(
    ID      BIGSERIAL PRIMARY KEY,
    TEXT    VARCHAR,
    CREATOR BIGINT NOT NULL
);

ALTER TABLE mems
    ADD CONSTRAINT creator_fk FOREIGN KEY (CREATOR) REFERENCES users (id);


CREATE TABLE TAGS
(
    ID   BIGSERIAL PRIMARY KEY,
    TEXT VARCHAR
);

CREATE TABLE MEMS_TAGS
(
    MEM_ID BIGINT,
    TAG_ID BIGINT
);

ALTER TABLE MEMS_TAGS
    ADD CONSTRAINT mt_mems_fk FOREIGN KEY (MEM_ID) REFERENCES MEMS (id);
ALTER TABLE MEMS_TAGS
    ADD CONSTRAINT mt_tags_fk FOREIGN KEY (TAG_ID) REFERENCES TAGS (id);

ALTER TABLE MEMS_TAGS
    ADD PRIMARY KEY (MEM_ID, TAG_ID);


CREATE TABLE MEMS_MEDIA
(
    MEM_ID BIGINT,
    MEDIA  varchar
);

ALTER TABLE MEMS_MEDIA
    ADD CONSTRAINT mm_mems_fk FOREIGN KEY (MEM_ID) REFERENCES MEMS (id);

