CREATE TABLE VIEWS
(
    MEM_ID  BIGINT,
    USER_ID BIGINT
);

ALTER TABLE VIEWS
    ADD CONSTRAINT views_mems_fk FOREIGN KEY (MEM_ID) REFERENCES MEMS (id);
ALTER TABLE VIEWS
    ADD CONSTRAINT views_user_fk FOREIGN KEY (USER_ID) REFERENCES USERS (id);

ALTER TABLE VIEWS
    ADD PRIMARY KEY (MEM_ID, USER_ID);